### ISSUE TITLE
Cannot build with VS2019

### ISSUE THREAD

**Issue by chong1144** [Ubpa/RayTracingToy#1]
## When I build the INSTALL, some errors occur
![image](https://user-images.githubusercontent.com/35533252/68987140-d5cc3000-0861-11ea-8a22-467a94f2eb62.png)
It seems `size_t` is `long long`, however `GLUint` is `unsigned long` in x64

How to solve this problem?

**Comment by Ubpa** [comment]
size_t 改为 unsigned int

**Comment by Ubpa** [comment]
I fix it at #4.
