### ISSUE TITLE
Building problem

### ISSUE THREAD

**Issue by Untitled** [Ubpa/RayTracingToy#4]
Hello I'm using VS 2019 (MSVC v142) to build this powerful ray tracing toy.
At first it told me "size_t *" cannot convert to "GLuint *", similar to #1 issue.
After replacing all "size_t" to "unsigned int", no more compiling errors issued.
However, this time hundreds of errors came out because of linking. It said LNK2019 Unresolved symbol, such as ![image](https://user-images.githubusercontent.com/33189830/86735718-91e2a100-c065-11ea-8d39-bf0f658778a1.png) .
There was 32 warnings also,
![image](https://user-images.githubusercontent.com/33189830/86735967-c0f91280-c065-11ea-8e6b-205f0434fbb4.png) LNK4272
Every warning has serveral errors following.
Can anyone help me with that?
Many thanks

**Comment by Ubpa** [comment]
Sorry, at that time I am not familiar with CMake.
Here is the solution:
After you click "Configure" button in CMake-GUI, you should choose **Win32** platform in the window "CMakeSetup".

**Comment by Ubpa** [comment]
I also fix a bug in vs2019 (at that time, I use vs2017)
I build it successfully just now.
(Sorry, this is my first project on GitHub, and  I hasn't maintained it for a long time.)

**Comment by Untitled** [comment]
thanks a lot

________________________________
发件人: Ubpa <notifications@github.com>
发送时间: 2020年7月13日 10:25
收件人: Ubpa/ToyRTX <ToyRTX@noreply.github.com>
抄送: ChapterII <cphms@outlook.com>; Author <author@noreply.github.com>
主题: Re: [Ubpa/ToyRTX] Building problem (#4)


Sorry, at that time I am not familiar with CMake.
Here is the solution:
After you click configure in CMake-GUI, you should choose Win32 platform in the window "CMakeSetup".

―
